language: ruby

rvm:
  - jruby-9.1.5.0
  - jruby-head

sudo: false

before_install:
  - gem install bundler
  - gem update bundler

install: travis_retry bundle install

script:
  - bundle exec rake spec

branches:
  only:
    - master
